// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU_NCIYWRDOdRqbXSfXFmpGdkZFj1TDeY',
    appId: '1:1079639568334:web:e3352f7cfdc2b84c7e859f',
    messagingSenderId: '1079639568334',
    projectId: 'wisataku-38006',
    authDomain: 'wisataku-38006.firebaseapp.com',
    databaseURL: 'https://wisataku-38006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wisataku-38006.appspot.com',
    measurementId: 'G-EGBNEKLX76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMHkWkt5iQfIqteSYCjCK9uP3kuFvOCdM',
    appId: '1:1079639568334:android:f002c220833c9fbd7e859f',
    messagingSenderId: '1079639568334',
    projectId: 'wisataku-38006',
    databaseURL: 'https://wisataku-38006-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wisataku-38006.appspot.com',
  );
}
